name: CI/CD Estimate Pro

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/registry"
  FRONTEND_IMAGE: "estimate-pro-frontend"
  FRONTEND_CONTAINER: "estimate-pro-frontend-container"
  BACKEND_IMAGE: "estimate-pro-backend"
  BACKEND_CONTAINER: "estimate-pro-backend-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate unified tag
        id: tag
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)-$(date +%Y%m%d-%H%M%S)
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "🏷️ Generated tag: ${TAG_NAME}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Selectel Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Frontend Image
        run: |
          docker buildx build \
            --target production \
            --no-cache \
            --push \
            --tag $REGISTRY/$FRONTEND_IMAGE:${{ steps.tag.outputs.tag }} \
            --tag $REGISTRY/$FRONTEND_IMAGE:latest \
            --file docker/frontend.Dockerfile \
            .
            
      - name: Build and Push Backend Image
        run: |
          docker buildx build \
            --target production \
            --no-cache \
            --push \
            --tag $REGISTRY/$BACKEND_IMAGE:${{ steps.tag.outputs.tag }} \
            --tag $REGISTRY/$BACKEND_IMAGE:latest \
            --file docker/backend.Dockerfile \
            .
  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Cloud
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: FRONTEND_IMAGE,BACKEND_IMAGE,REGISTRY,FRONTEND_CONTAINER,BACKEND_CONTAINER
          script: |
            # Set up variables
            TAG_NAME="${{ needs.image-build-and-push.outputs.tag }}"
            
            echo "🚀 Starting deployment..."
            echo "📦 Frontend: $REGISTRY/$FRONTEND_IMAGE:$TAG_NAME"
            echo "📦 Backend: $REGISTRY/$BACKEND_IMAGE:$TAG_NAME"
            
            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
            # Pull new images
            echo "📥 Pulling new images..."
            docker pull $REGISTRY/$FRONTEND_IMAGE:$TAG_NAME
            docker pull $REGISTRY/$BACKEND_IMAGE:$TAG_NAME
            
            # Navigate to project directory
            cd ~/tgma/estimate-pro
            
            # Запуск через Docker Compose
            echo "🚀 Running docker compose..."
            ../../deploy.sh $TAG_NAME
            
            # Verify deployment
            echo "✅ Verifying deployment..."
            docker ps | grep estimate-pro || echo "Warning: containers not found"
            
            echo "🎉 Deployment completed!"